### ISSUE TITLE
Get error when compile deepin-wm >=1.9.25

### ISSUE THREAD

**Issue by zhtengw** [linuxdeepin/deepin-wm#33]
I got " no member named ‘tile’" error when compile deepin-wm. Can anyone help me to deal with this problem?

```
x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I/var/tmp/portage/x11-wm/deepin-wm-1.9.27/work/deepin-wm-1.9.27/src -I..  -include ../config.h -DDATADIR=\"/usr/share\" -DPKGDATADIR=\"/usr/share/deepin-wm\" -DLIBDIR=\"/usr/lib64\" -DPKGLIBDIR=\"/usr/lib64/deepin-wm\" -DPLUGINDIR=\"/usr/lib64/deepin-wm/plugins\" -DWM_SCHEMA=\"com.deepin.wrap.gnome.desktop.wm\" -DSCHEMA=\"com.deepin.wrap.pantheon.desktop.gala\" -DDEEPIN_SCHEMA=\"com.deepin.dde\" -DDEEPIN_XSETTINGS_SCHEMA=\"com.deepin.xsettings\"   -pthread -I/usr/include/gtk-3.0 -I/usr/include/libbamf3 -I/usr/lib64/libbamf3/include -I/usr/include/clutter-gtk-1.0 -I/usr/include/deepin-mutter -I/usr/include/clutter-1.0 -I/usr/include/cogl -I/usr/include/json-glib-1.0 -I/usr/include/gnome-desktop-3.0 -I/usr/include/granite -I/usr/include/gee-0.8 -I/usr/include/libwnck-3.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/libdrm -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gsettings-desktop-schemas -include config.h -w -DGNOME_DESKTOP_USE_UNSTABLE_API -I../lib  -march=native -O2 -pipe -Wl,--enable-new-dtags -c -o gala-WorkspaceManager.o `test -f 'WorkspaceManager.c' || echo '/var/tmp/portage/x11-wm/deepin-wm-1.9.27/work/deepin-wm-1.9.27/src/'`WorkspaceManager.c
/var/tmp/portage/x11-wm/deepin-wm-1.9.27/work/deepin-wm-1.9.27/src/WindowManager.vala: In function ‘gala_window_manager _gala_class_init’:
/var/tmp/portage/x11-wm/deepin-wm-1.9.27/work/deepin-wm-1.9.27/src/WindowManager.vala:724:29: error: ‘MetaPluginClass { aka struct _MetaPluginClass}’ has no member named ‘tile’
  public class WindowManagerGala : Meta.Plugin, WindowManager
```

**Comment by sonald** [comment]
@zhtengw build with deepin-mutter at least 3.20.30

**Comment by zhtengw** [comment]
Thanks, solved!
